using UnityEngine;

/// <summary>
/// Tracks player noise level for AI hearing detection.
/// Noise is generated by movement (walking, sprinting, jumping).
/// </summary>
public class PlayerNoise : MonoBehaviour
{
    public static PlayerNoise Instance { get; private set; }

    [Header("Noise Settings")]
    [SerializeField] private float baseNoiseRadius = 1f;       // Standing still (breathing, small sounds)
    [SerializeField] private float walkNoiseRadius = 8f;       // Walking
    [SerializeField] private float sprintNoiseRadius = 15f;    // Sprinting
    [SerializeField] private float crouchNoiseRadius = 3f;     // Crouching movement
    [SerializeField] private float jumpNoiseRadius = 12f;      // Landing from jump
    [SerializeField] private float jumpNoiseDuration = 0.5f;   // How long jump noise lasts

    [Header("Debug")]
    [SerializeField] private bool showNoiseGizmo = true;

    // Current noise state
    public float CurrentNoiseRadius { get; private set; }
    public bool IsMakingNoise => CurrentNoiseRadius > 0.1f;

    private Rigidbody rb;
    private float jumpNoiseTimer;
    private bool wasGrounded = true;
    private float groundCheckRadius = 0.3f;
    private float groundCheckDistance = 0.1f;

    private void Awake()
    {
        Instance = this;
        rb = GetComponent<Rigidbody>();
    }

    private void Update()
    {
        UpdateNoiseLevel();
    }

    private void UpdateNoiseLevel()
    {
        // Handle jump noise timer
        if (jumpNoiseTimer > 0f)
        {
            jumpNoiseTimer -= Time.deltaTime;
            CurrentNoiseRadius = jumpNoiseRadius;
            return;
        }

        // Check movement velocity
        float horizontalSpeed = 0f;
        if (rb != null)
        {
            Vector3 horizontalVelocity = new Vector3(rb.linearVelocity.x, 0, rb.linearVelocity.z);
            horizontalSpeed = horizontalVelocity.magnitude;
        }

        // Check if grounded (for landing detection)
        bool isGrounded = CheckGrounded();

        // Detect landing
        if (isGrounded && !wasGrounded)
        {
            TriggerJumpNoise();
        }
        wasGrounded = isGrounded;

        // Calculate noise based on movement
        if (horizontalSpeed < 0.1f)
        {
            CurrentNoiseRadius = baseNoiseRadius;
        }
        else if (horizontalSpeed > 6f) // Sprint threshold
        {
            CurrentNoiseRadius = sprintNoiseRadius;
        }
        else if (IsCrouching())
        {
            CurrentNoiseRadius = crouchNoiseRadius;
        }
        else
        {
            CurrentNoiseRadius = walkNoiseRadius;
        }
    }

    private bool CheckGrounded()
    {
        return Physics.SphereCast(
            transform.position + Vector3.up * groundCheckRadius,
            groundCheckRadius * 0.9f,
            Vector3.down,
            out _,
            groundCheckDistance + groundCheckRadius
        );
    }

    private bool IsCrouching()
    {
        // Check if player scale is reduced (crouch detection from FirstPersonController)
        return transform.localScale.y < 0.9f;
    }

    /// <summary>
    /// Trigger a loud noise event (e.g., from landing, knocking something over)
    /// </summary>
    public void TriggerJumpNoise()
    {
        jumpNoiseTimer = jumpNoiseDuration;
        CurrentNoiseRadius = jumpNoiseRadius;
    }

    /// <summary>
    /// Trigger a custom noise with specified radius and duration
    /// </summary>
    public void TriggerNoise(float radius, float duration)
    {
        if (radius > CurrentNoiseRadius)
        {
            jumpNoiseTimer = duration;
            CurrentNoiseRadius = radius;
        }
    }

#if UNITY_EDITOR
    private void OnDrawGizmosSelected()
    {
        if (!showNoiseGizmo) return;

        // Draw noise radius
        Gizmos.color = IsMakingNoise ? new Color(1f, 0.5f, 0f, 0.3f) : new Color(0f, 1f, 0f, 0.1f);
        Gizmos.DrawWireSphere(transform.position, CurrentNoiseRadius);

        if (IsMakingNoise)
        {
            UnityEditor.Handles.color = new Color(1f, 0.5f, 0f, 0.15f);
            UnityEditor.Handles.DrawSolidDisc(transform.position, Vector3.up, CurrentNoiseRadius);
        }
    }
#endif
}
